#coding=utf-8
"""
Django settings for yuntest project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5+%1&+4ng5%=@(w300b#dbu_dfxd-)e5azcj)ay0tqde1g*)yc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'account',
    'qiniuyun',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yuntest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yuntest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases


if 'SERVER_SOFTWARE' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'RXgYLzhdUYuMneOJwVjw',
            'USER': '62b4bac3959e4b9e983ce38d058f8e73',
            'PASSWORD': 'bf0767545e88486c9c32e2e77d309fcf',
            'HOST': 'sqld.duapp.com',
            'PORT': '4050',
            }
        }
else:    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'OPTIONS':{
                'read_default_file': os.path.join(BASE_DIR, 'db.cnf'),
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
    from local_settings import email_conf,qiniu_conf
#  ---------------------------------------------------------
# qiniu settigs for upload used by 'qiniuyun.sevencow'
# https://github.com/qiniu/python-sdk
# django-qiniu-storage https://github.com/glasslion/django-qiniu-storage
    
    QINIU_CONF=qiniu_conf
    QINIU_ACCESS_KEY=qiniu_conf['access_key']	#七牛给开发者分配的 AccessKey
    QINIU_SECRET_KEY=qiniu_conf['secret_key']	#七牛给开发者分配的 Secret
    QINIU_BUCKET_NAME=qiniu_conf['bucket_name']	#用来存放文件的七牛空间(bucket)的名字
    QINIU_BUCKET_DOMAIN=qiniu_conf['bucket_domain']
#  ---------------------------------------------------------    
#  ---------------------------------------------------------
#  Email ,ref:http://www.cnblogs.com/BeginMan/p/3443158.html
    EMAIL_BACKEND = email_conf["EMAIL_BACKEND"]
 
    EMAIL_USE_TLS = email_conf["EMAIL_USE_TLS"]
    EMAIL_HOST = email_conf["EMAIL_HOST"]
    EMAIL_PORT = email_conf["EMAIL_PORT"]
    EMAIL_HOST_USER = email_conf["EMAIL_HOST_USER"]
    EMAIL_HOST_PASSWORD = email_conf["EMAIL_HOST_PASSWORD"]
    DEFAULT_FROM_EMAIL = email_conf["DEFAULT_FROM_EMAIL"]
#  ---------------------------------------------------------

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace("\\", "/")
#MEDIA_URL = '/media/'




